# Introduction to Numpy

## Creating Numpy Arrays

In [1]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [23]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

In [7]:
# np.arange(start(inclusive), stop(non-inclusive), step)
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# np.zeros((rows, columns))
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# linspace returns array from start, stop, and number of items
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
# np.eye creates an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# creating arrays of random numbers, using a uniform distribution with size argument
np.random.rand(5)

array([0.578147  , 0.51507452, 0.45579244, 0.06931919, 0.63817779])

In [16]:
np.random.rand(5, 5)

array([[9.85818234e-02, 6.85224358e-01, 1.75744056e-01, 6.42570401e-01,
        1.98908790e-01],
       [1.94003166e-01, 3.85829760e-01, 5.03781448e-02, 4.18001290e-01,
        5.84346319e-01],
       [6.86684673e-01, 8.17541354e-01, 8.36361848e-01, 6.64887004e-01,
        9.16033632e-01],
       [5.82450089e-01, 8.49589613e-02, 4.02530211e-01, 7.58155647e-02,
        1.30963899e-01],
       [9.93646399e-02, 6.74758774e-02, 4.22808265e-01, 9.37362784e-01,
        5.37416684e-04]])

In [17]:
# standard normal distribution
np.random.randn(2)

array([ 0.5708771, -1.2236144])

In [18]:
np.random.randn(5, 5)

array([[-2.85187091,  2.28921226,  0.67407097, -0.16773239, -0.83909853],
       [ 1.05167815, -0.40706077,  0.32573625, -2.54435474,  1.81351886],
       [-1.66256423, -0.50361441,  1.16291307, -0.86823749, -0.42313695],
       [-1.25129967, -1.37146216, -0.40183748,  1.34854766,  0.53585346],
       [-2.11545442,  1.00449642,  0.64007016,  0.78619721, -0.16223398]])

In [19]:
# random integers (low inclusive, high exclusive, number of items)
np.random.randint(1, 100, 10)

array([25, 10, 10, 95, 63, 32, 92, 35, 47, 57])

## Array Attributes and Methods

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
ranarr

array([ 2, 29, 23,  2, 49, 30, 47,  9, 21, 43])

In [22]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

49

In [32]:
ranarr.argmax()

4

In [33]:
ranarr.argmin()

0

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1, 25).shape

(1, 25)

In [37]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [40]:
arr.dtype

dtype('int64')

## Bracket Indexing and Selection

In [41]:
arr=np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# get value at an index
arr[8]

8

In [44]:
# get value in a range
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

## Broadcasting
Numpy arrays differ from normal python lists because of their ability to broadcast

In [46]:
# Setting a value with index range (broadcasting)
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Note that the new changes also occur in the original array;
Data is not copied - it's a view of the original array;
Avoids memory problems

In [54]:
# Be explicit to get a copy
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy[0] = 10
arr_copy

array([10, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)
General format is arr_2d[row][col] or arr_2d[row, col]

In [57]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
# Indexing by row
arr_2d[1]

array([20, 25, 30])

In [59]:
arr_2d[1][1]

25

In [60]:
arr_2d[1, 1]

25

In [67]:
#2d array slicing, shape from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
# Boolean indexing
bool_arr = arr > 5

In [71]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [73]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr[arr>8]

array([99, 99, 99, 99, 99, 99,  9, 10])

### Fancy indexing

In [63]:
# Set up matrix
arr2d = np.zeros((10, 10))

In [64]:
# length of array
arr_length = arr2d.shape[1]

In [65]:
# Set up array 
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [76]:
arr2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [78]:
# Allows any order :)
arr2d[[6, 4, 2, 7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## NumPy Operations

### Arithmetic

In [79]:
arr = np.arange(0, 10)

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
# Warning on division by 0
arr/arr

/anaconda3/envs/udemy_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
# Warning, not an error but instead infinity
1/arr

/anaconda3/envs/udemy_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [85]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array Functions
Numpy comes with some universal array functions - mathmatical operations that you can use to perform an operation across an array

In [86]:
# Taking square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [88]:
# Calculating e^ value
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [89]:
np.max(arr) # same as arr.max()

9

In [90]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [91]:
np.log(arr)

/anaconda3/envs/udemy_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

https://numpy.org/doc/stable/reference/ufuncs.html